# Generated by Django 2.0 on 2018-12-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank='True', default='0000-00-00 00:00:00')),
                ('name', models.TextField(default='Not', max_length=20)),
                ('surname', models.TextField(default='Not', max_length=20)),
                ('fathername', models.TextField(default='Not', max_length=20)),
                ('description', models.TextField(default='Not', max_length=200)),
                ('phone', models.IntegerField(blank='True', default=0)),
            ],
        ),
    ]
